#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
VisDiff — Noise Interpolation (3-panel GIF per sample)

Left:   best polygon (by F1) from batch sample #1
Middle: polygons generated by *noise* interpolation between the two best noises
Right:  best polygon (by F1) from batch sample #2

- Constant axes (square bounds over all frames) so the middle box doesn't jump
- Plot style:
    blue edges (lw=10), viridis-colored vertices (ms=20), axes off, equal aspect
- True transparent GIF with no outer whitespace (manual RGBA frames + Pillow)
- Picks the best *valid* polygon (else best overall) when converting SDF->vertices
"""

import os
import math
import copy
import pickle
import numpy as np
from itertools import tee
import warnings
warnings.simplefilter("ignore", DeprecationWarning)
import torch
import matplotlib
matplotlib.use("Agg")  # headless-friendly
import matplotlib.pyplot as plt
from matplotlib import animation
from shapely.geometry import Polygon, LineString
from multiprocessing import Pool
from sklearn.metrics import f1_score
from PIL import Image

# SDF -> contour helpers
import cv2
import visvalingamwyatt as vw

# ---------------------- Repro & Device ----------------------
torch.manual_seed(123)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(123)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ---------------------- Diffusion Schedule ----------------------
class Schedule:
    def __init__(self, sigmas: torch.FloatTensor):
        self.sigmas = sigmas
    def __getitem__(self, i) -> torch.FloatTensor:
        return self.sigmas[i]
    def __len__(self) -> int:
        return len(self.sigmas)
    def sample_batch(self, x0: torch.FloatTensor) -> torch.FloatTensor:
        return self[torch.randint(len(self), (x0.shape[0],))].to(x0)
    def sample_sigmas(self, steps: int) -> torch.FloatTensor:
        indices = list((len(self) * (1 - np.arange(0, steps)/steps)).round().astype(np.int64) - 1)
        return self[indices + [0]]

class ScheduleLogLinear(Schedule):
    def __init__(self, N: int, sigma_min: float=0.02, sigma_max: float=10):
        super().__init__(torch.logspace(math.log10(sigma_min), math.log10(sigma_max), N))

def pairwise(iterable):
    a, b = tee(iterable)
    next(b, None)
    return zip(a, b)

# ---------------------- Sampler ----------------------
@torch.no_grad()
def samples(model, condition, sigmas, gam, mu, xt, batchsize):
    """
    Model forward: model(xt, sig, visibility=condition, ...)
    If xt is provided, denoise starting from that; else draw Gaussian start.
    Returns final xt (SDF) and the start noise (for the None-xt case).
    """
    start = None
    if xt is None:
        xt = (torch.randn((batchsize, 1, 44, 44), device=DEVICE) * sigmas[0]).to(DEVICE)
        start = xt.clone()
    eps_prev = None
    for i, (sig, sig_prev) in enumerate(pairwise(sigmas)):
        eps = model(xt, sig.to(DEVICE), visibility=condition, encoder_hidden_states=None, output_dict=False)
        eps_av = eps if (i == 0 or eps_prev is None) else (eps * gam + eps_prev * (1 - gam))
        eps_prev = eps
        sig_p = (sig_prev/sig**mu)**(1/(1-mu))
        eta = (sig_prev**2 - sig_p**2).sqrt()
        xt = xt - (sig - sig_p) * eps_av + eta * torch.randn_like(xt)
    return xt, start

# ---------------------- Visibility (same as your snippet) ----------------------
class Visibility_Calculator:
    def line_segments_intersect(self, seg1, seg2):
        p1, p2 = np.array(seg1[0]), np.array(seg1[1])
        q1, q2 = np.array(seg2[0]), np.array(seg2[1])
        r = p2 - p1
        s = q2 - q1
        denominator = np.cross(r, s)
        if np.isclose(denominator, 0):
            return False
        t_numer = np.cross(q1 - p1, s)
        u_numer = np.cross(q1 - p1, r)
        t = t_numer / denominator
        u = u_numer / denominator
        return (0 <= t <= 1) and (0 <= u <= 1)

    def line_outside_polygon_non_valid(self, line, polygon):
        length = line.length
        midpoint = line.interpolate(length / 2)
        return not polygon.contains(midpoint)

    def process_row(self, args):
        row_index, coords, poly = args
        visibility_row = np.zeros(len(coords))
        for j in range(row_index + 1, len(coords)):
            if j - row_index == 1 or (row_index == 0 and j == len(coords) - 1):
                continue
            flag = True
            line = LineString([coords[row_index], coords[j]])
            for x in range(coords.shape[0]):
                if x != row_index and x != j and (x+1) % len(coords) != row_index and (x+1) % len(coords) != j:
                    edge = LineString([coords[x], coords[(x+1) % len(coords)]])
                    if self.line_segments_intersect(list(line.coords), list(edge.coords)) and not line.touches(edge):
                        flag = False
                        break
            if flag and self.line_outside_polygon_non_valid(line, poly):
                flag = False
            if flag:
                visibility_row[j] = 1
        return visibility_row

    def visibility_matrix_generator(self, coords):
        poly = Polygon(coords)
        n = len(coords)
        vg = np.zeros((n, n))
        np.fill_diagonal(vg, 1)
        vg += np.diag(np.ones(n-1), k=1)
        vg += np.diag(np.ones(n-1), k=-1)
        vg[0, -1] = vg[-1, 0] = 1

        args_list = [(i, coords, poly) for i in range(n)]
        pool = Pool()
        results = pool.map(self.process_row, args_list)
        pool.close(); pool.join()

        upper = np.zeros((n, n))
        for i, row in enumerate(results):
            upper[i] = row
        vg += upper + upper.T
        return (vg > 0.5).astype(np.float32)

# ---------------------- SDF → polygon initializations ----------------------
def _interp_to_n(points, n=25):
    """Resample a polyline to exactly n points (no SciPy dependency)."""
    if points.shape[0] == n:
        return points
    d = np.cumsum(np.linalg.norm(np.diff(points, axis=0), axis=1))
    d = np.insert(d, 0, 0.0)
    t = np.linspace(0.0, d[-1], n)
    x = np.interp(t, d, points[:, 0])
    y = np.interp(t, d, points[:, 1])
    return np.stack([x, y], axis=-1)

def sdf_polygon_generation(sdf: np.ndarray, band=0.1, target_n=25, scale=0.05) -> torch.Tensor:
    """
    Extract a |sdf|<band contour, simplify to ~target_n (Visvalingam–Whyatt),
    resample to exactly target_n if needed, then build cyclic + reversed variants.
    Returns (M, target_n, 2) tensor.
    """
    mask = ((sdf > -band) & (sdf < band)).astype(np.uint8) * 255
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        # small fallback square
        pts = np.array([[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]], np.float32)
    else:
        largest = max(contours, key=cv2.contourArea)
        pts = np.array([p[0] for p in largest], dtype=np.float32)
        simp = vw.Simplifier(pts).simplify(number=target_n)
        pts = simp * scale
        if pts.shape[0] < target_n:
            pts = _interp_to_n(pts, n=target_n)

    cands = []
    for k in range(len(pts)):
        cands.append(np.roll(pts, k, axis=0))
        cands.append(np.roll(pts[::-1], k, axis=0))
    return torch.tensor(np.stack(cands, axis=0), dtype=torch.float32)

# ---------------------- Best valid (else best) vertex recovery ----------------------
# @torch.no_grad()
# def vertices_from_sdf(vertices_generator, sdf_t: torch.Tensor, cond_tensor: torch.Tensor) -> np.ndarray:
#     """
#     Generate multiple candidate polygons from an SDF by running the vertex head.
#     Select the best *valid* polygon by F1 vs the target visibility.
#     If none valid, pick the best overall; else fall back to the first.
#     """
#     from sklearn.metrics import f1_score

#     def unpack_visibility(cond_vec: torch.Tensor, V: int) -> np.ndarray:
#         u = cond_vec.detach().float().view(-1).cpu().numpy()
#         M = np.zeros((V, V), dtype=np.float32)
#         idx = 0
#         for r in range(V):
#             for c in range(r, V):
#                 M[r, c] = u[idx]
#                 M[c, r] = u[idx]
#                 idx += 1
#         np.fill_diagonal(M, 1.0)
#         return (M >= 0.5).astype(np.float32)

#     sdf_np = sdf_t.detach().squeeze().cpu().numpy()      # (H,W)
#     init_pts = sdf_polygon_generation(sdf_np)             # (M,V,2)
#     M, V, _ = init_pts.shape

#     sdf_rep  = torch.tensor(sdf_np, dtype=torch.float32, device=DEVICE).unsqueeze(0).unsqueeze(0).repeat(M, 1, 1, 1)
#     cond_rep = cond_tensor.to(DEVICE).repeat(M, 1)
#     init_pts = init_pts.to(DEVICE)

#     offs = vertices_generator(init_pts, cond_rep, sdf_rep)   # (M,V,2) offsets
#     finals = (init_pts + offs).detach().cpu().numpy()        # (M,V,2)

#     target_vis = unpack_visibility(cond_tensor, V)
#     vis_calc = Visibility_Calculator()

#     best_valid_idx, best_valid_score = None, -np.inf
#     best_any_idx, best_any_score = None, -np.inf

#     for b in range(M):
#         pts = finals[b]
#         score = -np.inf
#         is_valid = False
#         try:
#             poly = Polygon(pts)
#             is_valid = (poly.is_valid and (not poly.is_empty) and (poly.area > 1e-8))
#             pred_vis = vis_calc.visibility_matrix_generator(pts)
#             score = f1_score(target_vis.flatten(), pred_vis.flatten(), average="macro")
#         except Exception:
#             pass

#         if score > best_any_score:
#             best_any_score, best_any_idx = score, b
#         if is_valid and score > best_valid_score:
#             best_valid_score, best_valid_idx = score, b

#     if best_valid_idx is not None:
#         return finals[best_valid_idx]
#     if best_any_idx is not None:
#         return finals[best_any_idx]
#     return finals[0]

@torch.no_grad()
def vertices_from_sdf(vertices_generator, sdf_t: torch.Tensor, cond_tensor: torch.Tensor) -> np.ndarray:
    """
    Build candidate initializations from SDF → run vertex head (predicts offsets) → choose first valid polygon.
    Args:
      sdf_t: (1,1,H,W) torch
      cond_tensor: (1,D)
    Returns:
      (V,2) numpy array (chosen polygon). Falls back to first if none valid.
    """
    sdf_np = sdf_t.detach().squeeze().cpu().numpy()  # (H,W)
    init_pts = sdf_polygon_generation(sdf_np)        # (M,V,2)
    M, V, _ = init_pts.shape

    sdf_rep  = torch.tensor(sdf_np, dtype=torch.float32, device=DEVICE).unsqueeze(0).unsqueeze(0).repeat(M, 1, 1, 1)
    cond_rep = cond_tensor.to(DEVICE).repeat(M, 1)
    init_pts = init_pts.to(DEVICE)

    offs = vertices_generator(init_pts, cond_rep, sdf_rep)   # (M,V,2)
    final_batch = (init_pts + offs).detach().cpu().numpy()   # (M,V,2)

    for b in range(M):
        pts = final_batch[b]
        try:
            poly = Polygon(pts)
            if poly.is_valid and not poly.is_empty and poly.area > 1e-8:
                return pts
        except Exception:
            pass
    return final_batch[0]

# ---------------------- Bounds helper ----------------------
def compute_global_square_bounds(polys, pad_ratio=0.06):
    """Square bounds that contain all polygons (with padding)."""
    pts_all = [p for p in polys if p is not None and len(p) > 0]
    if not pts_all:
        return (-1, 1, -1, 1)
    stack = np.vstack(pts_all)
    minx, miny = stack.min(0)
    maxx, maxy = stack.max(0)
    dx, dy = maxx - minx, maxy - miny
    side = max(dx, dy)
    pad = pad_ratio * (side if side > 0 else 1.0)
    cx, cy = (minx + maxx) / 2.0, (miny + maxy) / 2.0
    half = 0.5 * side + pad
    return (cx - half, cx + half, cy - half, cy + half)


# ---------------------- Three-panel GIF (transparent, no whitespace) ----------------------
def animate_start_middle_end(
    start_polygon,
    generated_polygons,     # list of (V,2) arrays, one per flip/frame
    end_polygon,
    flip_indices=None,      # ignored now
    out_gif="Visdiff_Triangulation_Propagation_3panel.gif",
    fps=2,
    figsize=(24, 6)
):
    """GIF: [Start | Generated(step k) | End] with CONSTANT axes and a single step label."""
    assert len(generated_polygons) > 0, "generated_polygons is empty."

    # ---- constant axes bounds across all frames ----
    def compute_global_square_bounds(polys, pad_ratio=0.06):
        pts_all = [p for p in polys if p is not None and len(p) > 0]
        if not pts_all:
            return (-1, 1, -1, 1)
        stack = np.vstack(pts_all)
        minx, miny = stack.min(0)
        maxx, maxy = stack.max(0)
        dx = maxx - minx; dy = maxy - miny
        side = max(dx, dy)
        pad = pad_ratio * (side if side > 0 else 1.0)
        cx = (minx + maxx) / 2.0; cy = (miny + maxy) / 2.0
        half = 0.5 * side + pad
        return (cx - half, cx + half, cy - half, cy + half)

    xmin, xmax, ymin, ymax = compute_global_square_bounds(
        [start_polygon, end_polygon] + generated_polygons, pad_ratio=0.06
    )

    fig, axes = plt.subplots(1, 3, figsize=figsize)
    for ax in axes:
        ax.set_xlim(xmin, xmax)
        ax.set_ylim(ymin, ymax)
        ax.set_aspect("equal", adjustable='box')
        ax.axis('off')

    # Leave extra headroom; put the step label above the plots
    fig.subplots_adjust(top=0.86, wspace=0.10)
    step_text = fig.text(0.5, 0.93, "", ha="center", va="top", fontsize=28, fontweight="bold")

    # --- plotting style (matches your snippet) ---
    def _plot_polygon_style(ax, polygon, title=None):
        ax.cla()
        ax.set_xlim(xmin, xmax); ax.set_ylim(ymin, ymax)
        if polygon is not None and len(polygon) > 0:
            colormap = plt.cm.get_cmap('viridis', len(polygon))
            ax.plot(polygon[:,0], polygon[:,1], color="blue", linewidth=10)
            ax.plot([polygon[-1,0], polygon[0,0]],
                    [polygon[-1,1], polygon[0,1]],
                    color="blue", linewidth=10)
            for i, (x, y) in enumerate(polygon):
                ax.plot(x, y, marker="o", color=colormap(i), markersize=20)
        if title is not None:
            ax.set_title(title, fontsize=24, weight="bold")
        ax.axis('off')
        ax.set_aspect('equal', adjustable='box')

    def init():
        _plot_polygon_style(axes[0], start_polygon, title="Start")
        _plot_polygon_style(axes[2], end_polygon,   title="End")
        _plot_polygon_style(axes[1], generated_polygons[0], title=None)  # no middle title
        step_text.set_text(f"Step 1/{len(generated_polygons)}")
        return []

    def update(k):
        _plot_polygon_style(axes[0], start_polygon, title="Start")
        _plot_polygon_style(axes[2], end_polygon,   title="End")
        _plot_polygon_style(axes[1], generated_polygons[k], title=None)  # no middle title
        step_text.set_text(f"Step {k+1}/{len(generated_polygons)}")
        return []

    anim = animation.FuncAnimation(
        fig, update, init_func=init,
        frames=len(generated_polygons), interval=1000/fps, blit=False
    )
    anim.save(out_gif, writer=animation.PillowWriter(fps=fps))
    print(f"Saved GIF: {out_gif}")
    plt.close(fig)


# def animate_interpolation_three_panel_gif(
#     start_polygon,            # (V,2)
#     frames_polygons,          # list[(V,2)] for each frame
#     end_polygon,              # (V,2)
#     out_gif,                  # path ending with .gif
#     fps=12,
#     figsize=(24, 8)
# ):
#     assert len(frames_polygons) > 0, "frames_polygons is empty."

#     xmin, xmax, ymin, ymax = compute_global_square_bounds(
#         [start_polygon, end_polygon] + list(frames_polygons), pad_ratio=0.06
#     )

#     fig = plt.figure(figsize=figsize, facecolor="none")
#     fig.patch.set_alpha(0)
#     gs = fig.add_gridspec(1, 3, left=0.0, right=1.0, bottom=0.0, top=1.0, wspace=0.02)
#     axL = fig.add_subplot(gs[0, 0])
#     axC = fig.add_subplot(gs[0, 1])
#     axR = fig.add_subplot(gs[0, 2])

#     for ax in (axL, axC, axR):
#         ax.set_facecolor('none')
#         ax.set_xlim(xmin, xmax); ax.set_ylim(ymin, ymax)
#         ax.set_aspect('equal', adjustable='box'); ax.axis('off')

#     step_text = axC.text(0.5, 0.98, "", transform=axC.transAxes,
#                          ha="center", va="top", fontsize=24, fontweight="bold", color="black")

#     def _draw(ax, polygon, title=None):
#         ax.lines.clear(); ax.collections.clear(); ax.patches.clear(); ax.images.clear()
#         if polygon is not None and len(polygon) > 0:
#             cmap = plt.cm.get_cmap('viridis', len(polygon))
#             ax.plot(polygon[:, 0], polygon[:, 1], color="blue", linewidth=10)
#             ax.plot([polygon[-1, 0], polygon[0, 0]],
#                     [polygon[-1, 1], polygon[0, 1]],
#                     color="blue", linewidth=10)
#             for i, (x, y) in enumerate(polygon):
#                 ax.plot(x, y, marker="o", color=cmap(i), markersize=20)
#         if title:
#             ax.set_title(title, fontsize=22, weight="bold", color="black", pad=6)

#     # Initial frame
#     _draw(axL, start_polygon, "Start")
#     _draw(axC, frames_polygons[0], None)
#     _draw(axR, end_polygon, "End")
#     step_text.set_text(f"Step 1/{len(frames_polygons)}")

#     frames = []
#     fig.canvas.draw()
#     frames.append(Image.fromarray(np.asarray(fig.canvas.buffer_rgba()), mode="RGBA"))

#     for k in range(1, len(frames_polygons)):
#         _draw(axL, start_polygon, "Start")
#         _draw(axC, frames_polygons[k], None)
#         _draw(axR, end_polygon, "End")
#         step_text.set_text(f"Step {k+1}/{len(frames_polygons)}")
#         fig.canvas.draw()
#         frames.append(Image.fromarray(np.asarray(fig.canvas.buffer_rgba()), mode="RGBA"))

#     frames[0].save(
#         out_gif,
#         save_all=True,
#         append_images=frames[1:],
#         loop=0,
#         duration=int(1000 / fps),
#         disposal=2  # restore to background (prevents trails)
#     )
#     plt.close(fig)

# ---------------------- Load models ----------------------
sdf_generator = torch.load(
    "/projects/standard/isleri/mahes092/Polygon_Dataset_Generator/Models/SDF_Diffusion_Normalized_Visibility/sdf_generator_epoch-60.pt",
    weights_only=False, map_location=DEVICE
).to(DEVICE).eval()

# vertex head must accept (init_pts, cond_rep, sdf_rep) -> offsets
vertices_generator = torch.load(
    "/projects/standard/isleri/mahes092/Polygon_Dataset_Generator/Models/Vertex_Trained_Model_Visibility/sdf_vertices_generator_best.pt",
    weights_only=False, map_location=DEVICE
).to(DEVICE).eval()

# ---------------------- Main loop (NOISE interpolation) ----------------------
test_dataset = "/projects/standard/isleri/mahes092/Polygon_Dataset_Generator/Minimum_Feature_25_Dataset_Test_New/"
schedule = ScheduleLogLinear(N=200, sigma_min=0.005, sigma_max=10)
sigmas = schedule.sample_sigmas(100).to(DEVICE)

evaluation_plots = {}
os.makedirs("Evaluation_GIFs_Interpolation_Noise", exist_ok=True)

def pack_upper_tri(M: np.ndarray) -> torch.Tensor:
    vals = []
    n = M.shape[0]
    for r in range(n):
        for c in range(r, n):
            vals.append(M[r, c])
    return torch.tensor(vals, dtype=torch.float32, device=DEVICE).unsqueeze(0)

def _to_noise_tensor(noise_np) -> torch.Tensor:
    """Ensure noise is (1,1,44,44) torch on DEVICE."""
    arr = np.asarray(noise_np, dtype=np.float32)
    if arr.ndim == 2:
        arr = arr[None, None, ...]
    elif arr.ndim == 3:
        arr = arr[None, ...]
    return torch.tensor(arr, device=DEVICE)

for each_file in os.listdir(test_dataset):
    full_path = os.path.join(test_dataset, each_file)
    if not os.path.isfile(full_path):
        continue

    with open(full_path, 'rb') as f:
        polygon_dict = pickle.load(f)

    final_level_2_visibility = polygon_dict["level_2_visibility"]
    vis_vec = []
    for r in range(final_level_2_visibility.shape[0]):
        for c in range(r, final_level_2_visibility.shape[1]):
            vis_vec.append(final_level_2_visibility[r, c])
    actual_visibility = torch.tensor(vis_vec, dtype=torch.float32, device=DEVICE).unsqueeze(0)
    print("started")
    # Sample a batch of SDFs (and capture the start noise)
    no_samples = 20
    visibility_batch = actual_visibility.repeat(no_samples, 1)
    generated_sdf_batch, start_noise = samples(
        sdf_generator, visibility_batch, sigmas, 1.0, 0.5, None, no_samples
    )

    # Recover vertices for each SDF sample using best-valid selector
    sdf_np_batch = generated_sdf_batch.detach().cpu()
    noise_np_batch = start_noise.detach().cpu().numpy()  # (B,1,44,44)

    final_vertices_generated_batch = []
    print("started 1")
    for b in range(no_samples):
        sdf_t = generated_sdf_batch[b:b+1]  # (1,1,44,44)
        pts = vertices_from_sdf(vertices_generator, sdf_t, actual_visibility)
        final_vertices_generated_batch.append(pts)
    final_vertices_generated_batch = np.asarray(final_vertices_generated_batch)  # (B,V,2)
    print("here 2")
    # Pick BEST and SECOND-BEST by F1
    best_acc = None
    best_vertices = None
    best_sdf = None
    best_noise = None
    best_pred_vis = None

    second_vertices = None
    second_sdf = None
    second_noise = None
    second_pred_vis = None

    vis_calc = Visibility_Calculator()
    for b in range(no_samples):
        poly_b = final_vertices_generated_batch[b]
        pred_vis_b = vis_calc.visibility_matrix_generator(poly_b)
        acc_b = f1_score(final_level_2_visibility.flatten(), pred_vis_b.flatten(), average="macro")

        if (best_acc is None) or (acc_b > best_acc):
            # shift current best to second-best
            if best_acc is not None:
                second_vertices = copy.deepcopy(best_vertices)
                second_sdf = copy.deepcopy(best_sdf)
                second_noise = copy.deepcopy(best_noise)
                second_pred_vis = copy.deepcopy(best_pred_vis)

            best_acc = acc_b
            best_vertices = copy.deepcopy(poly_b)
            best_sdf = sdf_np_batch[b, 0].numpy()          # (44,44)
            best_noise = noise_np_batch[b]                 # (1,44,44)
            best_pred_vis = copy.deepcopy(pred_vis_b)

        # initialize second-best on very first pass
        if second_vertices is None and best_vertices is not None and best_vertices is not poly_b:
            second_vertices = copy.deepcopy(best_vertices)
            second_sdf = copy.deepcopy(best_sdf)
            second_noise = copy.deepcopy(best_noise)
            second_pred_vis = copy.deepcopy(best_pred_vis)

    # If we never found a distinct second-best, duplicate best (still works)
    if second_noise is None:
        second_vertices = copy.deepcopy(best_vertices)
        second_sdf = copy.deepcopy(best_sdf)
        second_noise = copy.deepcopy(best_noise)
        second_pred_vis = copy.deepcopy(best_pred_vis)
    print("here 1")
    # --- NOISE INTERPOLATION (not SDF) ---
    steps = 20
    interpolated_polygons = []
    interpolated_visibility = []
    bn = _to_noise_tensor(best_noise)        # (1,1,44,44)
    bn1 = _to_noise_tensor(second_noise)     # (1,1,44,44)

    for i in range(steps):
        t = i / (steps - 1)  # 0..1 inclusive
        xt_t = t * bn + (1.0 - t) * bn1      # blend the *noise*
        sdf_t, _ = samples(sdf_generator, actual_visibility, sigmas, 1.0, 0.5, xt_t, 1)
        
        verts_t = vertices_from_sdf(vertices_generator, sdf_t, actual_visibility)  # (V,2)
        pred_vis_t = vis_calc.visibility_matrix_generator(verts_t)

        interpolated_polygons.append(verts_t)
        interpolated_visibility.append(pred_vis_t)

    # Save metrics & data for this file
    current_file = {
        "predicted_polygon_1": second_vertices,
        "predicted_polygon_2": best_vertices,
        "predicted_visibility_1": second_pred_vis,
        "predicted_visibility_2": best_pred_vis,
        "predicted_interpolated_polygons": np.array(interpolated_polygons),
        "predicted_interpolated_visibility": np.array(interpolated_visibility),
    }
    evaluation_plots[each_file] = current_file
    print("here")
    # 3-panel GIF (left = second_best, middle = noise-interp frames, right = best)
    base = os.path.splitext(os.path.basename(each_file))[0]
    out_gif = os.path.join("Evaluation_GIFs_Interpolation_Noise", f"{base}_interp_noise_3panel.gif")

    animate_start_middle_end(
    start_polygon=np.asarray(second_vertices),
    generated_polygons=[np.asarray(p) for p in interpolated_polygons],
    end_polygon=np.asarray(best_vertices),
    flip_indices=None,              # optional / ignored
    out_gif=out_gif,
    fps=2,
    figsize=(24, 8)
)

    print(f"Saved GIF: {out_gif}")

# Save pickle of all samples
with open('Visdiff_Predictions_Interpolations_Noise.pkl', 'wb') as f:
    pickle.dump(evaluation_plots, f)
print("Wrote: Visdiff_Predictions_Interpolations_Noise.pkl")
